browse_url:
  description:
    Open a URL in the default browser on the host machine of Open Peer Power
  fields:
    url:
      name: URL
      description: The URL to open.
      required: true
      example: "https://www.openpeerpower.io"
      selector:
        text:
